apiVersion: apps/v1
kind: Deployment
metadata:
  name: livestream1
  labels:
    app: livestream1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livestream1
  template:
    metadata:
      labels:
        app: livestream1
    spec:
      nodeSelector:
      containers:
      - image: mspoccr.azurecr.io/live_stream_vehicle:2.0
        name: livestream1
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: vechicle
      
      


