azure_storage_connectionstring: "DefaultEndpointsProtocol=https;AccountName=msstorageblob;AccountKey=4p3NNT34CzPXoYAlDF4+7GNFHTJBv9zV+1D7rFIUIiLH0r7iLNc9ikz9BTwt+v4cpMoQufXd/98x+ASt3kAJoA==;EndpointSuffix=core.windows.net"
process_container_name: "processvideo"
Traffic_mon_url: 'https://highwaymonitoringwebapi.azurewebsites.net/api/Vehicletrend'