Account: "https://mspocdb.documents.azure.com:443/"
Key: "R79EBwOGMIbYFnwFXbN33p1eLX30uLVAT1XnIckuxpaZ7y9ZXa1LGaRTeHHD3jIJYuzzTo21cq9NLxHPqPf9uw=="
DatabaseName: "HighwayMonitoringSystem2"
containerName: "VehicleTrendingLive"